#!/bin/bash

log=/var/log/update-script.log

#This colour
cyan='\e[0;36m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'

if [[ $USER != 'root' ]]; then
	echo -e $yellow"Maaf, Anda harus menjalankan ini sebagai root"
	exit
fi

# initialisasi var
export DEBIAN_FRONTEND=noninteractive
OS=`uname -m`;
MYIP=$(wget -qO- ipv4.icanhazip.com);
MYIP2="s/xxxxxxxxx/$MYIP/g";
ether=`ifconfig | cut -c 1-8 | sort | uniq -u | grep venet0 | grep -v venet0:`
if [[ $ether = "" ]]; then
        ether=eth0
fi

#vps="zvur";
vps="aneka";

if [[ $vps = "zvur" ]]; then
	source="http://scripts.gapaiasa.com"
else
	source="http://vpsproject.me/site5/Debian7"
fi

# text gambar
apt-get install boxes

# color text
cd
rm -rf /root/bashrc
wget -O /root/.bashrc  $source/bashrc

# install lolcat
sudo apt-get -y install ruby
sudo gem install lolcat
cd
echo -e $yellow "[ ! ]  Proses Updating Script VPS .....  "
echo -e $yellow "[ ! ]  ................     Please wait  "
wget -O /usr/bin/motd $source/motd >> $log 2>&1
wget -O /usr/bin/benchmark $source/benchmark.sh >> $log 2>&1
wget -O /usr/bin/speedtest $source/speedtest_cli.py" >> $log 2>&1
wget -O /usr/bin/ps-mem $source/ps_mem.py >> $log 2>&1
wget -O /usr/bin/dropmon $source/dropmon.sh >> $log 2>&1
wget -O /usr/bin/menu $source/menu.sh >> $log 2>&1
wget -O /usr/bin/user-active-list $source/user-active-list.sh >> $log 2>&1
wget -O /usr/bin/user-add $source//user-add.sh >> $log 2>&1
wget -O /usr/bin/user-add-pptp $source/user-add-pptp.sh >> $log 2>&1
wget -O /usr/bin/user-del $source/user-del.sh >> $log 2>&1
wget -O /usr/bin/disable-user-expire $source/disable-user-expire.sh >> $log 2>&1
wget -O /usr/bin/delete-user-expire $source/delete-user-expire.sh >> $log 2>&1
wget -O /usr/bin/banned-user $source/banned-user.sh >> $log 2>&1
wget -O /usr/bin/unbanned-user $source/unbanned-user.sh >> $log 2>&1
wget -O /usr/bin/user-expire-list $source/user-expire-list.sh >> $log 2>&1
wget -O /usr/bin/user-gen $source/user-gen.sh >> $log 2>&1
wget -O /usr/bin/userlimit.sh $source/userlimit.sh >> $log 2>&1
wget -O /usr/bin/userlimitssh.sh $source/userlimitssh.sh >> $log 2>&1
wget -O /usr/bin/user-list $source/user-list.sh >> $log 2>&1
wget -O /usr/bin/user-login $source/user-login.sh >> $log 2>&1
wget -O /usr/bin/user-pass $source/user-pass.sh >> $log 2>&1
wget -O /usr/bin/user-renew $source/user-renew.sh >> $log 2>&1
wget -O /usr/bin/clearcache.sh $source/clearcache.sh >> $log 2>&1
wget -O /usr/bin/bannermenu $source/bannermenu >> $log 2>&1
cd

#rm -rf /etc/cron.weekly/
#rm -rf /etc/cron.hourly/
#rm -rf /etc/cron.monthly/
rm -rf /etc/cron.daily/
wget -O /root/passwd $source/passwd.sh >> $log 2>&1
chmod +x /root/passwd
echo "01 23 * * * root /root/passwd" > /etc/cron.d/passwd

echo "*/30 * * * * root service dropbear restart" > /etc/cron.d/dropbear
echo "00 23 * * * root /usr/bin/disable-user-expire" > /etc/cron.d/disable-user-expire
echo "0 */12 * * * root /sbin/reboot" > /etc/cron.d/reboot
#echo "00 01 * * * root echo 3 > /proc/sys/vm/drop_caches && swapoff -a && swapon -a" > /etc/cron.d/clearcacheram3swap
echo "*/30 * * * * root /usr/bin/clearcache.sh" > /etc/cron.d/clearcache1

cd
chmod +x /usr/bin/motd >> $log 2>&1
chmod +x /usr/bin/benchmark >> $log 2>&1
chmod +x /usr/bin/speedtest >> $log 2>&1
chmod +x /usr/bin/ps-mem >> $log 2>&1
#chmod +x /usr/bin/autokill >> $log 2>&1
chmod +x /usr/bin/dropmon >> $log 2>&1
chmod +x /usr/bin/menu >> $log 2>&1
chmod +x /usr/bin/user-active-list >> $log 2>&1
chmod +x /usr/bin/user-add >> $log 2>&1
chmod +x /usr/bin/user-add-pptp >> $log 2>&1
chmod +x /usr/bin/user-del >> $log 2>&1
chmod +x /usr/bin/disable-user-expire >> $log 2>&1
chmod +x /usr/bin/delete-user-expire >> $log 2>&1
chmod +x /usr/bin/banned-user >> $log 2>&1
chmod +x /usr/bin/unbanned-user >> $log 2>&1
chmod +x /usr/bin/user-expire-list >> $log 2>&1
chmod +x /usr/bin/user-gen >> $log 2>&1
chmod +x /usr/bin/userlimit.sh >> $log 2>&1
chmod +x /usr/bin/userlimitssh.sh >> $log 2>&1
chmod +x /usr/bin/user-list >> $log 2>&1
chmod +x /usr/bin/user-login >> $log 2>&1
chmod +x /usr/bin/user-pass >> $log 2>&1
chmod +x /usr/bin/user-renew >> $log 2>&1
chmod +x /usr/bin/clearcache.sh >> $log 2>&1
chmod +x /usr/bin/bannermenu >> $log 2>&1
echo -e $lightgreen "[ ✔ ]  Script Now Updated     "
echo -e $white "Terimakasih SUdah Menggunakan Script ./VpsProject"
rm update.sh
history -c
